# Yarn configuration file
# Disable Plug'n'Play and use traditional node_modules structure

# Disable PnP (Plug'n'Play) - use node_modules instead
nodeLinker: node-modules

# Set install mode to skip builds for faster installs (optional)
enableGlobalCache: true

# Network settings
httpTimeout: 60000

# Compression settings for better performance
compressionLevel: mixed

# Enable immutable installs in CI environments
enableImmutableInstalls: false
# Cache folder location (optional - uses default if not specified)
# cacheFolder: "./.yarn/cache"

# Plugin settings (if you need any plugins, uncomment and configure)
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs

# Registry settings (uses npm registry by default)
# npmRegistryServer: "https://registry.npmjs.org"

# Workspace settings (if this becomes a monorepo)
# enableWorkspaces: true
